### ISSUE TITLE
tabbar is behind content

### ISSUE THREAD

**Issue by dcsan** [dcsan/moflow#2]
![image](https://cloud.githubusercontent.com/assets/514002/7692863/0fb2de34-fd7e-11e4-9ca0-b6402ca80e79.png)

I think this is because we're mixing a famous core 'header footer' view and a flex view, which seem to control their layering differently.

its probably possible to get them to work together, but maybe better to just use the [TabBar controller](https://github.com/IjzerenHein/famous-flex-tabbarcontroller/blob/master/tutorial/TabBarController.md) here.

**Comment by dcsan** [comment]
using CSS seems to be the only way to make this work

![image](https://cloud.githubusercontent.com/assets/514002/7693258/9f5a1caa-fd83-11e4-9680-b5c0944ef672.png)

**Comment by dcsan** [comment]
@sayawan FYI.

**Comment by kakajansh** [comment]
#### Why is my surface behind this second surface?

##### There are a few reasons this could happen.
1. The order in which surfaces are instantiated can affect surface display order. Surfaces that are instantiated first end up being rendered behind newer surfaces because their associated DOM element is created first.
2. Famo.us translations could be affecting your surface’s position. Check your code to see if you have any modifiers affecting your surface’s translation in z-space.
3. CSS z-indexing can also affect the display position of surfaces. Look carefully at any CSS you might have included in your application that includes z-index properties. For surfaces that share the same translation in z-space, default DOM layering will be overridden by explicit CSS z-index values.

from [Common Questions](http://famo.us/docs/reference/pages/0.3/common-questions.html)

the reason was:  `famous.utilities.Utility.transformInFront` I saw its usage from famous twitter clone, but it was actually removed from `utilities`. So instead:

``` js
navbar.state = new StateModifier({
    // transform: Transform.inFront
    transform: Transform.traslate(0, 0, 10)
});
```

and it is also good to define in css as you did:

``` css
.ff-tabbar {
  background-color: #FF00cc;
  z-index: 100;
}
```

and the reason why `Transform.inFront` didnt work. It just equal to  `Transform.translate(0,0,1)`. So we had the same in our scrollview. 

``` js
scrollView.state = new StateModifier({
     ....
     transform: Transform.translate(0,0,1)
});
```
